version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: vms-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vms_db
      POSTGRES_USER: vms_user
      POSTGRES_PASSWORD: vms_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vms_user -d vms_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
