spring:
  application:
    name: VMS
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource: 
    url: jdbc:postgresql://db:5432/vms_db
    username: vms_user
    password: vms_password
    driver-class-name: org.postgresql.Driver

gg:
  jte:
    developmentMode: true

visitor:
  system:
    otp:
      subject: OTP Verification Code
