spring:
#  datasource:
#    # Database Configuration (PostgreSQL)
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: password

server:
  # Server Configuration
  port: "443"
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${PASSWORD}
    key-store-type: PKCS12
    key-alias: myalias
    # SSL/TLS Configuration (commented examples)
    #enabled-protocols: TLSv1.2
    #ciphers: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256