spring:
  application:
    name: VMS
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: https://graph.microsoft.com/.default
        provider:
          azure:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  error:
    whitelabel:
      enabled: false

visitor:
  system:
    notification:
      email: test@email.com
      subject: New Visitor Registration
    otp:
      subject: OTP Verification Code
    employee:
      notification:
        subject: YOUR VISITOR IS HERE

gg:
  jte:
    developmentMode: true
    precompile: false

vms:
  system-email: test@email.com
  admin-email: test@email.com
  sync:
    onstartup:
      enabled: false

graph:
  api:
    base-url: https://graph.microsoft.com/v1.0