spring:
  application:
    name: VMS
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: https://graph.microsoft.com/.default
        provider:
          azure:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration

visitor:
  system:
    notification:
      email: test@email.com
      subject: New Visitor Registration
    otp:
      subject: OTP Verification Code
    employee:
      notification:
        subject: YOUR VISITOR IS HERE
gg:
  jte:
    developmentMode: true

vms:
  system-email: test@email.com
  admin-email: test@email.com

mail:
  url: http://localhost:${wiremock.server.port}/v1.0/users/%s/sendMail
