spring:
  config:
    activate:
      on-profile: qa # This file is active when 'qa' profile is set

# In QA, we don't need actual Azure credentials or a sender email.
# The QaEmailService will log attempts instead of sending real emails.
# You can put dummy values or omit these sections entirely if the
# QaEmailService doesn't rely on them. Keeping them here ensures
# that @Value injections don't fail if they are present elsewhere
# in the application that might get called with the QA profile.

visitor:
  system:
    notification:
      email: qa_admin@example.com # Dummy value for QA
      subject: QA - New Visitor Registration # Clarify it's QA
    employee:
      notification:
        subject: QA - YOUR VISITOR IS HERE # Clarify it's QA

app:
  user-email: qa_sender@example.com # Dummy value for QA